# Securely send your logs to Loggly using TLS encryption. 
# https://www.loggly.com/docs/rsyslog-tls-configuration/

- name: Rsyslog | Install required software
  package:
    name: rsyslog-gnutls
    state: present
- name: Rsyslog | Create certificate folder for tls
  file:
    path: "{{ rsyslog_cert_path }}"
    state: directory
- name: Rsyslog | Download certificate
  debug: "msg=test"
#- name: Rsyslog | Download {{ rsyslog_srv }} certificate {{ services[rsyslog_srv].cert_path }}{{ services[rsyslog_srv].cert_name }}
#   get_url:
#     url: "{{ services[rsyslog_srv].cert_path }}{{ services[rsyslog_srv].cert_name }}"
#     dest: "{{ rsyslog_cert_path }}{{ rsyslog_cert }}"